"""Send AI news digest via SMTP email."""

from __future__ import annotations

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from ai_news_digest.config import Settings
from ai_news_digest.models import SummaryDigest

logger = logging.getLogger(__name__)

_TEMPLATE_DIR = Path(__file__).resolve().parent / "templates"


class EmailSender:
    """Render HTML digest and send via SMTP."""

    def __init__(self, settings: Settings):
        self.settings = settings
        self.cfg = settings.email
        self.jinja = Environment(
            loader=FileSystemLoader(str(_TEMPLATE_DIR)),
            autoescape=True,
        )

    def render_html(self, digest: SummaryDigest) -> str:
        """Render the digest into a styled HTML email body."""
        template = self.jinja.get_template("digest.html")
        return template.render(
            date=digest.date,
            total=digest.total_articles_fetched,
            overall_summary=digest.overall_summary,
            key_trends=digest.key_trends,
            article_summaries=digest.article_summaries,
        )

    def send(self, digest: SummaryDigest) -> bool:
        """Render and send the digest email. Returns True on success."""
        if not self.cfg.recipients:
            logger.error("No recipients configured — set email.recipients in config.yaml")
            return False

        sender = self.cfg.sender
        password = self.cfg.password
        if not sender or not password:
            logger.error(
                "Email credentials missing — set %s and %s in .env",
                self.cfg.sender_env, self.cfg.password_env,
            )
            return False

        subject = f"🤖 AI News Digest — {digest.date}"
        html_body = self.render_html(digest)

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = sender
        msg["To"] = ", ".join(self.cfg.recipients)

        # Plain-text fallback
        plain = self._plain_text(digest)
        msg.attach(MIMEText(plain, "plain", "utf-8"))
        msg.attach(MIMEText(html_body, "html", "utf-8"))

        try:
            with smtplib.SMTP(self.cfg.smtp_host, self.cfg.smtp_port, timeout=30) as server:
                server.ehlo()
                server.starttls()
                server.ehlo()
                server.login(sender, password)
                server.sendmail(sender, self.cfg.recipients, msg.as_string())
            logger.info("Email sent to %s", ", ".join(self.cfg.recipients))
            return True
        except smtplib.SMTPAuthenticationError:
            logger.error("SMTP auth failed — check email/password (use App Password for Gmail)")
            return False
        except smtplib.SMTPException as e:
            logger.error("SMTP error: %s", e)
            return False
        except Exception as e:
            logger.error("Email send failed: %s", e)
            return False

    def _plain_text(self, digest: SummaryDigest) -> str:
        """Generate plain-text version of the digest."""
        lines = [
            f"AI News Digest — {digest.date}",
            "=" * 40,
            "",
            digest.overall_summary,
            "",
        ]
        if digest.key_trends:
            lines.append("Key Trends:")
            for t in digest.key_trends:
                lines.append(f"  • {t}")
            lines.append("")

        lines.append("Articles:")
        lines.append("-" * 40)
        for a in digest.article_summaries:
            lines.append(f"\n■ {a.title}")
            lines.append(f"  Source: {a.source}")
            lines.append(f"  {a.summary}")
            if a.relevance:
                lines.append(f"  💡 {a.relevance}")
            lines.append(f"  Link: {a.url}")

        lines.append("\n---\nGenerated by AI News Digest")
        return "\n".join(lines)
